INSERT INTO types (item_name, name) VALUES 
("content", "page"), 
("content", "book"), 
("content", "post"), 
("content", "project"), 
("collection", "album"), 
("collection", "folder"), 
("resource", "embed"), 
("resource", "link"), 
("resource", "file"), 
("term", "section"), 
("term", "tag");

INSERT INTO types (key, value, activity, created, modified) VALUES 
("system_email", "pedrokoblitz@gmail.com", 2, NOW(), NOW()),
("per_page", "12", 2, NOW(), NOW()),
("upload_dir", "/public/media", 2, NOW(), NOW()),
("app_web_root", "/", 2, NOW(), NOW()),
("app_abs_path", "/var/www/html/", 2, NOW(), NOW()),
("panel_log_quantity", "15", 2, NOW(), NOW()),
("panel_content_quantity", "10", 2, NOW(), NOW()),
("panel_collection_quantity", "5", 2, NOW(), NOW()),
("panel_resource_quantity", "5", 2, NOW(), NOW()),
("panel_term_quantity", "5", 2, NOW(), NOW()),
("facebook_app_id", "", 2, NOW(), NOW()),
("facebook_auth_key", "", 2, NOW(), NOW()),
("facebook_auth_secret", "", 2, NOW(), NOW()),
("twitter_app_id", "", 2, NOW(), NOW()),
("twitter_app_key", "", 2, NOW(), NOW()),
("twitter_app_secret", "", 2, NOW(), NOW()),
("flickr_profile_url", "http://flickr.com.br/photos/pedrokoblitz", 2, NOW(), NOW()),
("tumblr_profile_url", "http://pedrokoblitz.tumblr.com", 2, NOW(), NOW()),
("facebook_profile_url", "https://facebook.com/pedrokoblitz", 2, NOW(), NOW()),
("twitter_profile_url", "http://twitter.com/pedrokoblitz", 2, NOW(), NOW()),
("linkedin_profile_url", "http://br.linkedin.com/pedrokoblitz", 2, NOW(), NOW()),
("pinterest_profile_url", "http://pinterest.com/pedrokoblitz", 2, NOW(), NOW());